### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [kaleidot725/ScrcpyHub#48]
What version works with Win 7?

Thanks

**Comment by kaleidot725** [comment]
I don't have windows7 machines. So that I don't know that ScrcpyHub run on Windows7. Please try to install and run ScrcpyHub on Windows7,

MSI File Download Link → https://github.com/kaleidot725/ScrcpyHub/releases/tag/v1.9.0

**Comment by kaleidot725** [comment]
We have no plans to officially support Windows 7, so we close this issue.
