### ISSUE TITLE
MacOS - with scrcpy and adb locations set, mirroring does not work (attempts to, then falls back to not doing it)

### ISSUE THREAD

**Issue by brett-james-rocketlab** [kaleidot725/ScrcpyHub#61]
Hello, 
Using this, It seems to stall on mirroring the screen.
which adb
and which scrcpy , get those locations and put them in the settings.

Fwiw, this is:
/opt/homebrew/bin/scrcpy
and /Users/myusername/Library/Android/sdk/platform-tools/adb

This is as far as I get, before the bottom button disapears.
![image](https://github.com/kaleidot725/ScrcpyHub/assets/95263021/0811a950-5670-4884-bb65-20d14cd9035c)

Using the terminal, I'm able to do scrcpy and see the output on my screen.

**Comment by LKHcoding** [comment]
same issue at m1 macOS (Ventura)

**Comment by kaleidot725** [comment]
Thanks for the report, v2.3.0 resolves this issue.
